format = "[// $directory$git_branch$conda$env_var//](fg:#374257)\n[// ](fg:#374257)"

[directory]
format="[⬢ ($path)]($style) "
style="#37A3FF"
truncate_to_repo = true

[git_branch]
format="[($symbol$branch)]($style) "
style="fg:#f49b4f"

[conda]
format="[($symbol$environment)]($style) "
style="fg:#905DFF"

[env_var]
format="[($symbol$env_value)]($style) "
variable="__NIX_PS1__"
style="#9DE6FF"
symbol="[❄️ ]($style)"

[character]
disabled=true

[battery]
disabled = true

scan_timeout = 10
add_newline = false
