# Main formatting configuration for display
format = "[// $directory$git_branch$python$env_var//](fg:#374257)\n[// ](fg:#374257)"

# Directory section configuration
[directory]
format = "[  ($path)]($style) "
style = "#37A3FF"
truncate_to_repo = true

# Git branch section configuration
[git_branch]
format = "[($symbol$branch)]($style) "
style = "fg:#f49b4f"

# Environment variable section configuration for __NIX_PS1__
[env_var]
format = "[($symbol$env_value)]($style) "
variable = "__NIX_PS1__"
style = "#9DE6FF"
symbol = "[❄ ]($style)"

# Python section configuration, only shows when virtualenv is active
[python]
format = "[$symbol( $virtualenv )]($style)"
style = "#D2A8FF"
symbol = ""
pyenv_version_name = true

# Character section configuration
[character]
disabled = true

# Battery section configuration
[battery]
disabled = true

# General settings
scan_timeout = 10
add_newline = false
