format = "[// $directory$git_branch$conda$python$env_var//](fg:#374257)\n[// ](fg:#374257)"

[directory]
format="[  ($path)]($style) "
style="#37A3FF"
truncate_to_repo = true

[git_branch]
format="[($symbol$branch)]($style) "
style="fg:#f49b4f"

[conda]
format="[($symbol$environment)]($style) "
style="fg:#905DFF"

[env_var]
format="[($symbol$env_value)]($style) "
variable="__NIX_PS1__"
style="#9DE6FF"
symbol="[❄ ]($style)"

[env_var.FLOX_PROMPT_ENVIRONMENTS]
format="[($symbol$env_value)]($style) "
style="#905DFF"
symbol="[❄ ]($style)"

[python]
format="[$symbol ($virtualenv)]($style) "
symbol = "[ ]($style)"
pyenv_version_name = false

[character]
disabled=true

[battery]
disabled = true

scan_timeout = 10
add_newline = false
